/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Geopolitics Intelligence Dashboard API
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  Country,
  CountryDetail,
  DashboardSummary,
  EconomyData,
  ErrorResponse,
  GetCountriesParams,
  GetNewsParams,
  HealthStatus,
  Leader,
  NewsArticle,
  RiskIndex,
  War,
  WarImpact,
  WarsSummary,
} from "./api.schemas";

import { customFetch } from "./custom-fetch";
import type { ErrorType } from "./custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get all countries
 */
export const getGetCountriesUrl = (params?: GetCountriesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/countries?${stringifiedParams}`
    : `/api/countries`;
};

export const getCountries = async (
  params?: GetCountriesParams,
  options?: RequestInit,
): Promise<Country[]> => {
  return customFetch<Country[]>(getGetCountriesUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetCountriesQueryKey = (params?: GetCountriesParams) => {
  return [`/api/countries`, ...(params ? [params] : [])] as const;
};

export const getGetCountriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getCountries>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCountriesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getCountries>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCountriesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCountries>>> = ({
    signal,
  }) => getCountries(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCountries>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCountriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCountries>>
>;
export type GetCountriesQueryError = ErrorType<unknown>;

/**
 * @summary Get all countries
 */

export function useGetCountries<
  TData = Awaited<ReturnType<typeof getCountries>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCountriesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getCountries>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetCountriesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get country detail
 */
export const getGetCountryUrl = (name: string) => {
  return `/api/countries/${name}`;
};

export const getCountry = async (
  name: string,
  options?: RequestInit,
): Promise<CountryDetail> => {
  return customFetch<CountryDetail>(getGetCountryUrl(name), {
    ...options,
    method: "GET",
  });
};

export const getGetCountryQueryKey = (name: string) => {
  return [`/api/countries/${name}`] as const;
};

export const getGetCountryQueryOptions = <
  TData = Awaited<ReturnType<typeof getCountry>>,
  TError = ErrorType<ErrorResponse>,
>(
  name: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getCountry>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCountryQueryKey(name);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCountry>>> = ({
    signal,
  }) => getCountry(name, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!name,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCountry>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCountryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCountry>>
>;
export type GetCountryQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get country detail
 */

export function useGetCountry<
  TData = Awaited<ReturnType<typeof getCountry>>,
  TError = ErrorType<ErrorResponse>,
>(
  name: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getCountry>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetCountryQueryOptions(name, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get current conflicts
 */
export const getGetWarsUrl = () => {
  return `/api/wars`;
};

export const getWars = async (options?: RequestInit): Promise<War[]> => {
  return customFetch<War[]>(getGetWarsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetWarsQueryKey = () => {
  return [`/api/wars`] as const;
};

export const getGetWarsQueryOptions = <
  TData = Awaited<ReturnType<typeof getWars>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getWars>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWarsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWars>>> = ({
    signal,
  }) => getWars({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWars>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetWarsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWars>>
>;
export type GetWarsQueryError = ErrorType<unknown>;

/**
 * @summary Get current conflicts
 */

export function useGetWars<
  TData = Awaited<ReturnType<typeof getWars>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getWars>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetWarsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Summary stats about wars
 */
export const getGetWarsSummaryUrl = () => {
  return `/api/wars/summary`;
};

export const getWarsSummary = async (
  options?: RequestInit,
): Promise<WarsSummary> => {
  return customFetch<WarsSummary>(getGetWarsSummaryUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetWarsSummaryQueryKey = () => {
  return [`/api/wars/summary`] as const;
};

export const getGetWarsSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof getWarsSummary>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getWarsSummary>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWarsSummaryQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWarsSummary>>> = ({
    signal,
  }) => getWarsSummary({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWarsSummary>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetWarsSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWarsSummary>>
>;
export type GetWarsSummaryQueryError = ErrorType<unknown>;

/**
 * @summary Summary stats about wars
 */

export function useGetWarsSummary<
  TData = Awaited<ReturnType<typeof getWarsSummary>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getWarsSummary>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetWarsSummaryQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get world leaders
 */
export const getGetLeadersUrl = () => {
  return `/api/leaders`;
};

export const getLeaders = async (options?: RequestInit): Promise<Leader[]> => {
  return customFetch<Leader[]>(getGetLeadersUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetLeadersQueryKey = () => {
  return [`/api/leaders`] as const;
};

export const getGetLeadersQueryOptions = <
  TData = Awaited<ReturnType<typeof getLeaders>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getLeaders>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLeadersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLeaders>>> = ({
    signal,
  }) => getLeaders({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLeaders>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetLeadersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLeaders>>
>;
export type GetLeadersQueryError = ErrorType<unknown>;

/**
 * @summary Get world leaders
 */

export function useGetLeaders<
  TData = Awaited<ReturnType<typeof getLeaders>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getLeaders>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetLeadersQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get global economy indicators
 */
export const getGetEconomyUrl = () => {
  return `/api/economy`;
};

export const getEconomy = async (
  options?: RequestInit,
): Promise<EconomyData> => {
  return customFetch<EconomyData>(getGetEconomyUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetEconomyQueryKey = () => {
  return [`/api/economy`] as const;
};

export const getGetEconomyQueryOptions = <
  TData = Awaited<ReturnType<typeof getEconomy>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getEconomy>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetEconomyQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getEconomy>>> = ({
    signal,
  }) => getEconomy({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getEconomy>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetEconomyQueryResult = NonNullable<
  Awaited<ReturnType<typeof getEconomy>>
>;
export type GetEconomyQueryError = ErrorType<unknown>;

/**
 * @summary Get global economy indicators
 */

export function useGetEconomy<
  TData = Awaited<ReturnType<typeof getEconomy>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getEconomy>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetEconomyQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get war economic impact data
 */
export const getGetWarImpactUrl = () => {
  return `/api/economy/war-impact`;
};

export const getWarImpact = async (
  options?: RequestInit,
): Promise<WarImpact> => {
  return customFetch<WarImpact>(getGetWarImpactUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetWarImpactQueryKey = () => {
  return [`/api/economy/war-impact`] as const;
};

export const getGetWarImpactQueryOptions = <
  TData = Awaited<ReturnType<typeof getWarImpact>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getWarImpact>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWarImpactQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWarImpact>>> = ({
    signal,
  }) => getWarImpact({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWarImpact>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetWarImpactQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWarImpact>>
>;
export type GetWarImpactQueryError = ErrorType<unknown>;

/**
 * @summary Get war economic impact data
 */

export function useGetWarImpact<
  TData = Awaited<ReturnType<typeof getWarImpact>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getWarImpact>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetWarImpactQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get news articles
 */
export const getGetNewsUrl = (params?: GetNewsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/news?${stringifiedParams}`
    : `/api/news`;
};

export const getNews = async (
  params?: GetNewsParams,
  options?: RequestInit,
): Promise<NewsArticle[]> => {
  return customFetch<NewsArticle[]>(getGetNewsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetNewsQueryKey = (params?: GetNewsParams) => {
  return [`/api/news`, ...(params ? [params] : [])] as const;
};

export const getGetNewsQueryOptions = <
  TData = Awaited<ReturnType<typeof getNews>>,
  TError = ErrorType<unknown>,
>(
  params?: GetNewsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getNews>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetNewsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getNews>>> = ({
    signal,
  }) => getNews(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getNews>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetNewsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getNews>>
>;
export type GetNewsQueryError = ErrorType<unknown>;

/**
 * @summary Get news articles
 */

export function useGetNews<
  TData = Awaited<ReturnType<typeof getNews>>,
  TError = ErrorType<unknown>,
>(
  params?: GetNewsParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getNews>>, TError, TData>;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetNewsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get dashboard summary stats
 */
export const getGetDashboardSummaryUrl = () => {
  return `/api/dashboard/summary`;
};

export const getDashboardSummary = async (
  options?: RequestInit,
): Promise<DashboardSummary> => {
  return customFetch<DashboardSummary>(getGetDashboardSummaryUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetDashboardSummaryQueryKey = () => {
  return [`/api/dashboard/summary`] as const;
};

export const getGetDashboardSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof getDashboardSummary>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardSummary>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDashboardSummaryQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDashboardSummary>>
  > = ({ signal }) => getDashboardSummary({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardSummary>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetDashboardSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDashboardSummary>>
>;
export type GetDashboardSummaryQueryError = ErrorType<unknown>;

/**
 * @summary Get dashboard summary stats
 */

export function useGetDashboardSummary<
  TData = Awaited<ReturnType<typeof getDashboardSummary>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardSummary>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetDashboardSummaryQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get global geopolitical risk index
 */
export const getGetRiskIndexUrl = () => {
  return `/api/dashboard/risk-index`;
};

export const getRiskIndex = async (
  options?: RequestInit,
): Promise<RiskIndex> => {
  return customFetch<RiskIndex>(getGetRiskIndexUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetRiskIndexQueryKey = () => {
  return [`/api/dashboard/risk-index`] as const;
};

export const getGetRiskIndexQueryOptions = <
  TData = Awaited<ReturnType<typeof getRiskIndex>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getRiskIndex>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRiskIndexQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRiskIndex>>> = ({
    signal,
  }) => getRiskIndex({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRiskIndex>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetRiskIndexQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRiskIndex>>
>;
export type GetRiskIndexQueryError = ErrorType<unknown>;

/**
 * @summary Get global geopolitical risk index
 */

export function useGetRiskIndex<
  TData = Awaited<ReturnType<typeof getRiskIndex>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getRiskIndex>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetRiskIndexQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
