import { Router } from "express";

const router = Router();

const countries = [
  {
    id: "ukraine",
    name: "Ukraine",
    code: "UA",
    region: "Europe",
    status: "war",
    flagUrl: "https://flagcdn.com/w40/ua.png",
    conflictSummary: "Ongoing Russian invasion since February 2022, major cities under bombardment.",
    riskScore: 9.4,
    gdp: 160,
    inflation: 18.7,
    population: 43000000,
  },
  {
    id: "russia",
    name: "Russia",
    code: "RU",
    region: "Europe",
    status: "war",
    flagUrl: "https://flagcdn.com/w40/ru.png",
    conflictSummary: "Engaged in military operations in Ukraine; facing international sanctions.",
    riskScore: 8.8,
    gdp: 1860,
    inflation: 7.3,
    population: 144000000,
  },
  {
    id: "israel",
    name: "Israel",
    code: "IL",
    region: "Middle East",
    status: "war",
    flagUrl: "https://flagcdn.com/w40/il.png",
    conflictSummary: "Active conflict in Gaza following October 7, 2023 Hamas attacks.",
    riskScore: 8.9,
    gdp: 509,
    inflation: 3.4,
    population: 9700000,
  },
  {
    id: "palestine",
    name: "Palestine",
    code: "PS",
    region: "Middle East",
    status: "war",
    flagUrl: "https://flagcdn.com/w40/ps.png",
    conflictSummary: "Gaza under siege; humanitarian crisis with over 2.2 million at risk.",
    riskScore: 9.8,
    gdp: 18,
    inflation: 22.1,
    population: 5200000,
  },
  {
    id: "sudan",
    name: "Sudan",
    code: "SD",
    region: "Africa",
    status: "war",
    flagUrl: "https://flagcdn.com/w40/sd.png",
    conflictSummary: "Civil war between SAF and RSF has displaced millions since April 2023.",
    riskScore: 9.2,
    gdp: 34,
    inflation: 63.2,
    population: 46000000,
  },
  {
    id: "myanmar",
    name: "Myanmar",
    code: "MM",
    region: "Asia",
    status: "war",
    flagUrl: "https://flagcdn.com/w40/mm.png",
    conflictSummary: "Military junta fighting multiple armed resistance groups across the country.",
    riskScore: 8.5,
    gdp: 65,
    inflation: 26.5,
    population: 54000000,
  },
  {
    id: "ethiopia",
    name: "Ethiopia",
    code: "ET",
    region: "Africa",
    status: "tension",
    flagUrl: "https://flagcdn.com/w40/et.png",
    conflictSummary: "Tigrayan peace deal fragile; Amhara conflict ongoing.",
    riskScore: 7.1,
    gdp: 126,
    inflation: 29.4,
    population: 126000000,
  },
  {
    id: "somalia",
    name: "Somalia",
    code: "SO",
    region: "Africa",
    status: "war",
    flagUrl: "https://flagcdn.com/w40/so.png",
    conflictSummary: "Al-Shabaab insurgency continues; fragile transitional government.",
    riskScore: 8.7,
    gdp: 8.3,
    inflation: 5.4,
    population: 17000000,
  },
  {
    id: "iran",
    name: "Iran",
    code: "IR",
    region: "Middle East",
    status: "tension",
    flagUrl: "https://flagcdn.com/w40/ir.png",
    conflictSummary: "Proxy conflicts across region; nuclear program tensions with West.",
    riskScore: 7.8,
    gdp: 413,
    inflation: 42.1,
    population: 87000000,
  },
  {
    id: "china",
    name: "China",
    code: "CN",
    region: "Asia",
    status: "tension",
    flagUrl: "https://flagcdn.com/w40/cn.png",
    conflictSummary: "Taiwan strait tensions; South China Sea territorial disputes escalating.",
    riskScore: 6.5,
    gdp: 17700,
    inflation: 0.7,
    population: 1400000000,
  },
  {
    id: "north-korea",
    name: "North Korea",
    code: "KP",
    region: "Asia",
    status: "tension",
    flagUrl: "https://flagcdn.com/w40/kp.png",
    conflictSummary: "Nuclear weapons tests and ballistic missile launches continue.",
    riskScore: 7.9,
    gdp: 16,
    inflation: null,
    population: 26000000,
  },
  {
    id: "taiwan",
    name: "Taiwan",
    code: "TW",
    region: "Asia",
    status: "tension",
    flagUrl: "https://flagcdn.com/w40/tw.png",
    conflictSummary: "Cross-strait military exercises increasing; sovereignty under pressure.",
    riskScore: 7.2,
    gdp: 760,
    inflation: 2.1,
    population: 23000000,
  },
  {
    id: "usa",
    name: "United States",
    code: "US",
    region: "Americas",
    status: "stable",
    flagUrl: "https://flagcdn.com/w40/us.png",
    conflictSummary: "Supporting allies in Ukraine and Israel; domestic political polarization.",
    riskScore: 3.8,
    gdp: 27360,
    inflation: 3.1,
    population: 335000000,
  },
  {
    id: "germany",
    name: "Germany",
    code: "DE",
    region: "Europe",
    status: "stable",
    flagUrl: "https://flagcdn.com/w40/de.png",
    conflictSummary: "Stable; energy transition challenges and economic slowdown.",
    riskScore: 2.4,
    gdp: 4080,
    inflation: 2.8,
    population: 84000000,
  },
  {
    id: "france",
    name: "France",
    code: "FR",
    region: "Europe",
    status: "stable",
    flagUrl: "https://flagcdn.com/w40/fr.png",
    conflictSummary: "Stable; political protests over pension reform resolved.",
    riskScore: 2.9,
    gdp: 2920,
    inflation: 2.4,
    population: 68000000,
  },
  {
    id: "uk",
    name: "United Kingdom",
    code: "GB",
    region: "Europe",
    status: "stable",
    flagUrl: "https://flagcdn.com/w40/gb.png",
    conflictSummary: "Stable post-Brexit; supporting Ukraine.",
    riskScore: 2.7,
    gdp: 3080,
    inflation: 3.9,
    population: 67000000,
  },
  {
    id: "india",
    name: "India",
    code: "IN",
    region: "Asia",
    status: "tension",
    flagUrl: "https://flagcdn.com/w40/in.png",
    conflictSummary: "Border tensions with Pakistan and China; rapid economic growth.",
    riskScore: 5.1,
    gdp: 3730,
    inflation: 4.8,
    population: 1428000000,
  },
  {
    id: "pakistan",
    name: "Pakistan",
    code: "PK",
    region: "Asia",
    status: "tension",
    flagUrl: "https://flagcdn.com/w40/pk.png",
    conflictSummary: "Political instability; TTP insurgency in northwest; economic crisis.",
    riskScore: 7.3,
    gdp: 341,
    inflation: 29.7,
    population: 231000000,
  },
  {
    id: "venezuela",
    name: "Venezuela",
    code: "VE",
    region: "Americas",
    status: "tension",
    flagUrl: "https://flagcdn.com/w40/ve.png",
    conflictSummary: "Economic collapse; authoritarian rule; mass migration crisis.",
    riskScore: 6.9,
    gdp: 92,
    inflation: 190,
    population: 28000000,
  },
  {
    id: "saudi-arabia",
    name: "Saudi Arabia",
    code: "SA",
    region: "Middle East",
    status: "stable",
    flagUrl: "https://flagcdn.com/w40/sa.png",
    conflictSummary: "Stable; normalization talks with Israel paused; oil revenues strong.",
    riskScore: 4.2,
    gdp: 1068,
    inflation: 1.7,
    population: 35000000,
  },
  {
    id: "japan",
    name: "Japan",
    code: "JP",
    region: "Asia",
    status: "stable",
    flagUrl: "https://flagcdn.com/w40/jp.png",
    conflictSummary: "Stable; increasing defense spending due to regional threats.",
    riskScore: 2.6,
    gdp: 4230,
    inflation: 2.9,
    population: 125000000,
  },
  {
    id: "brazil",
    name: "Brazil",
    code: "BR",
    region: "Americas",
    status: "stable",
    flagUrl: "https://flagcdn.com/w40/br.png",
    conflictSummary: "Stable; Amazon deforestation criticism; gang violence in cities.",
    riskScore: 3.9,
    gdp: 2080,
    inflation: 4.6,
    population: 215000000,
  },
  {
    id: "south-africa",
    name: "South Africa",
    code: "ZA",
    region: "Africa",
    status: "tension",
    flagUrl: "https://flagcdn.com/w40/za.png",
    conflictSummary: "High crime rate; rolling blackouts; coalition government fragility.",
    riskScore: 5.8,
    gdp: 399,
    inflation: 5.6,
    population: 60000000,
  },
  {
    id: "nigeria",
    name: "Nigeria",
    code: "NG",
    region: "Africa",
    status: "tension",
    flagUrl: "https://flagcdn.com/w40/ng.png",
    conflictSummary: "Boko Haram activity in northeast; banditry in northwest; economic strain.",
    riskScore: 6.7,
    gdp: 477,
    inflation: 26.7,
    population: 220000000,
  },
  {
    id: "mali",
    name: "Mali",
    code: "ML",
    region: "Africa",
    status: "war",
    flagUrl: "https://flagcdn.com/w40/ml.png",
    conflictSummary: "Jihadist insurgency; junta expelled French/UN forces; Wagner presence.",
    riskScore: 8.3,
    gdp: 19,
    inflation: 4.2,
    population: 22000000,
  },
  {
    id: "haiti",
    name: "Haiti",
    code: "HT",
    region: "Americas",
    status: "war",
    flagUrl: "https://flagcdn.com/w40/ht.png",
    conflictSummary: "Gang warfare controls 85% of Port-au-Prince; humanitarian catastrophe.",
    riskScore: 9.1,
    gdp: 21,
    inflation: 42.7,
    population: 11700000,
  },
];

router.get("/", (req, res) => {
  const { status, search, region } = req.query as Record<string, string>;
  let result = [...countries];

  if (status && status !== "all") {
    result = result.filter((c) => c.status === status);
  }
  if (region) {
    result = result.filter((c) =>
      c.region.toLowerCase().includes(region.toLowerCase())
    );
  }
  if (search) {
    const q = search.toLowerCase();
    result = result.filter(
      (c) => c.name.toLowerCase().includes(q) || c.code.toLowerCase().includes(q)
    );
  }

  res.json(result);
});

router.get("/:name", (req, res) => {
  const name = req.params.name.toLowerCase();
  const country = countries.find(
    (c) => c.id === name || c.name.toLowerCase() === name || c.code.toLowerCase() === name
  );

  if (!country) {
    res.status(404).json({ error: "not_found", message: `Country '${req.params.name}' not found` });
    return;
  }

  const conflictReasons: Record<string, string> = {
    ukraine: "Russia's full-scale invasion began February 24, 2022, following years of tensions over NATO expansion, the 2014 Maidan Revolution, and Russian annexation of Crimea. The conflict stems from Russia's opposition to Ukrainian sovereignty and Western integration.",
    russia: "Russia launched a 'special military operation' against Ukraine citing NATO expansion threats and the need to protect Russian-speaking populations in eastern Ukraine. The conflict has resulted in severe international sanctions.",
    israel: "The October 7, 2023 Hamas attack killed approximately 1,200 Israelis and took 240 hostages. Israel launched a comprehensive military campaign in Gaza. The conflict is rooted in decades of territorial disputes and the Palestinian-Israeli peace process breakdown.",
    palestine: "Gaza has been under blockade since 2007. The 2023-2024 conflict has caused massive civilian casualties and a humanitarian crisis, with the UN declaring famine conditions in northern Gaza.",
    sudan: "Tensions between the Sudanese Armed Forces (SAF) and the Rapid Support Forces (RSF) erupted into civil war in April 2023 following a power struggle during the democratic transition. Over 7 million people have been displaced.",
    myanmar: "Following the February 2021 military coup, multiple ethnic armed organizations and the People's Defence Force launched resistance operations. The junta's brutal crackdowns have escalated into a nationwide armed conflict.",
    ethiopia: "The Tigray War (2020-2022) between the federal government and the Tigray People's Liberation Front left over 500,000 dead. While a peace deal was signed, the Amhara conflict and Oromia insurgency continue.",
    somalia: "Al-Shabaab insurgency has persisted for over a decade, controlling large rural areas. The Federal Government of Somalia with AMISOM/ATMIS support has made gains in cities but rural areas remain contested.",
    iran: "Iran's support of Hamas, Hezbollah, Houthis, and Iraqi militias represents a regional proxy strategy. Nuclear enrichment to 60% purity has triggered Western sanctions. Revolutionary Guard operations inside neighboring countries continue.",
    china: "Taiwan strait tensions reached peak levels in 2023 following US Speaker Pelosi's visit. South China Sea territorial disputes with the Philippines, Vietnam, and Malaysia over artificial islands and energy resources continue escalating.",
    haiti: "Presidential assassination in 2021 created a power vacuum. Gang federation G9 now controls 80%+ of Port-au-Prince. A Kenyan-led multinational security support mission was deployed in 2024 but faces significant challenges.",
  };

  const economicData: Record<string, Record<string, number>> = {
    ukraine: { gdpGrowth: -29.1, unemployment: 24.5, currencyChange: -33.4, tradeBalance: -12.3, oilProduction: 0 },
    russia: { gdpGrowth: 3.6, unemployment: 3.2, currencyChange: -22.1, tradeBalance: 148.2, oilProduction: 9.5 },
    israel: { gdpGrowth: -1.9, unemployment: 8.1, currencyChange: -9.8, tradeBalance: -14.7, oilProduction: 0 },
    usa: { gdpGrowth: 2.5, unemployment: 3.9, currencyChange: 4.2, tradeBalance: -773, oilProduction: 13.2 },
    china: { gdpGrowth: 4.9, unemployment: 5.1, currencyChange: -2.8, tradeBalance: 823, oilProduction: 4.2 },
  };

  const detail = {
    ...country,
    conflictReason: conflictReasons[country.id] || `${country.name} has ongoing geopolitical challenges affecting regional stability.`,
    conflictStart: country.status === "war" ? "2022-02-24" : null,
    gdpGrowth: economicData[country.id]?.gdpGrowth ?? (Math.random() * 6 - 2),
    unemployment: economicData[country.id]?.unemployment ?? (Math.random() * 15 + 3),
    currency: "USD",
    currencyChange: economicData[country.id]?.currencyChange ?? (Math.random() * 20 - 10),
    tradeBalance: economicData[country.id]?.tradeBalance ?? (Math.random() * 100 - 50),
    oilProduction: economicData[country.id]?.oilProduction ?? 0,
    leader: null,
    news: [],
    warImpact: {
      gdpImpact: country.status === "war" ? -28.5 : -2.1,
      inflationImpact: country.status === "war" ? 12.3 : 0.8,
      tradeImpact: country.status === "war" ? -34.2 : -1.5,
      oilImpact: country.status === "war" ? 18.7 : 2.3,
      gdpTimeline: Array.from({ length: 8 }, (_, i) => ({
        date: `${2018 + i}`,
        value: 100 + (Math.random() * 20 - 10) * (i > 4 ? -2 : 1),
      })),
      inflationTimeline: Array.from({ length: 8 }, (_, i) => ({
        date: `${2018 + i}`,
        value: 3 + (i > 4 ? i * 3.5 : Math.random() * 2),
      })),
      tradeTimeline: Array.from({ length: 8 }, (_, i) => ({
        date: `${2018 + i}`,
        value: 50 - (i > 4 ? i * 5 : 0) + Math.random() * 10,
      })),
      energyTimeline: Array.from({ length: 8 }, (_, i) => ({
        date: `${2018 + i}`,
        value: 70 + (i > 4 ? i * 4 : 0) + Math.random() * 5,
      })),
    },
  };

  res.json(detail);
});

export default router;
