import { Router } from "express";

const router = Router();

const leaders = [
  {
    id: "biden",
    name: "Joe Biden",
    country: "United States",
    countryCode: "US",
    title: "President",
    photoUrl: "https://ui-avatars.com/api/?name=Joe+Biden&background=1e3a5f&color=93c5fd&size=128&bold=true&format=png",
    latestStatement: "We will continue to stand with our allies and defend the principles of democracy and sovereignty that have kept the peace for decades.",
    statementTimestamp: new Date(Date.now() - 3600000).toISOString(),
    impactLevel: "high",
    statementLink: "https://www.whitehouse.gov",
    party: "Democratic Party",
    inPowerSince: "2021-01-20",
  },
  {
    id: "putin",
    name: "Vladimir Putin",
    country: "Russia",
    countryCode: "RU",
    title: "President",
    photoUrl: "https://ui-avatars.com/api/?name=Vladimir+Putin&background=3b1a1a&color=fca5a5&size=128&bold=true&format=png",
    latestStatement: "Russia's special military operation will achieve all of its stated objectives. The West's attempts to isolate Russia have failed spectacularly.",
    statementTimestamp: new Date(Date.now() - 7200000).toISOString(),
    impactLevel: "high",
    statementLink: "http://kremlin.ru/en",
    party: "United Russia",
    inPowerSince: "2000-05-07",
  },
  {
    id: "xi",
    name: "Xi Jinping",
    country: "China",
    countryCode: "CN",
    title: "General Secretary",
    photoUrl: "https://ui-avatars.com/api/?name=Xi+Jinping&background=1a1a3b&color=c4b5fd&size=128&bold=true&format=png",
    latestStatement: "China's reunification is a historical inevitability. No foreign interference will alter the course of national rejuvenation.",
    statementTimestamp: new Date(Date.now() - 14400000).toISOString(),
    impactLevel: "high",
    statementLink: "http://www.xinhuanet.com/english",
    party: "Chinese Communist Party",
    inPowerSince: "2013-03-14",
  },
  {
    id: "khamenei",
    name: "Ali Khamenei",
    country: "Iran",
    countryCode: "IR",
    title: "Supreme Leader",
    photoUrl: "https://ui-avatars.com/api/?name=Ali+Khamenei&background=1a2e1a&color=86efac&size=128&bold=true&format=png",
    latestStatement: "The Zionist regime will not survive. The axis of resistance grows stronger every day and the enemies of Islam tremble before our resolve.",
    statementTimestamp: new Date(Date.now() - 18000000).toISOString(),
    impactLevel: "high",
    statementLink: "https://english.khamenei.ir",
    party: "Principlist",
    inPowerSince: "1989-06-04",
  },
  {
    id: "zelensky",
    name: "Volodymyr Zelensky",
    country: "Ukraine",
    countryCode: "UA",
    title: "President",
    photoUrl: "https://ui-avatars.com/api/?name=Volodymyr+Zelensky&background=1a2e3b&color=fde68a&size=128&bold=true&format=png",
    latestStatement: "Ukraine needs more air defense systems now. Every day without them, more of our people die. The world must act faster — not tomorrow, today.",
    statementTimestamp: new Date(Date.now() - 5400000).toISOString(),
    impactLevel: "high",
    statementLink: "https://www.president.gov.ua/en",
    party: "Servant of the People",
    inPowerSince: "2019-05-20",
  },
  {
    id: "netanyahu",
    name: "Benjamin Netanyahu",
    country: "Israel",
    countryCode: "IL",
    title: "Prime Minister",
    photoUrl: "https://ui-avatars.com/api/?name=Benjamin+Netanyahu&background=2e1a1a&color=fda4af&size=128&bold=true&format=png",
    latestStatement: "Israel will eliminate Hamas completely. There will be no ceasefire until all our hostages are returned and Hamas is destroyed as a military force.",
    statementTimestamp: new Date(Date.now() - 9000000).toISOString(),
    impactLevel: "high",
    statementLink: "https://www.gov.il/en",
    party: "Likud",
    inPowerSince: "2022-12-29",
  },
  {
    id: "modi",
    name: "Narendra Modi",
    country: "India",
    countryCode: "IN",
    title: "Prime Minister",
    photoUrl: "https://ui-avatars.com/api/?name=Narendra+Modi&background=2e1f0a&color=fdba74&size=128&bold=true&format=png",
    latestStatement: "India will become the world's third largest economy by 2027. Our strategic autonomy allows us to maintain balanced relationships with all global powers.",
    statementTimestamp: new Date(Date.now() - 21600000).toISOString(),
    impactLevel: "medium",
    statementLink: "https://www.pmindia.gov.in",
    party: "BJP",
    inPowerSince: "2014-05-26",
  },
  {
    id: "macron",
    name: "Emmanuel Macron",
    country: "France",
    countryCode: "FR",
    title: "President",
    photoUrl: "https://ui-avatars.com/api/?name=Emmanuel+Macron&background=0a1a2e&color=7dd3fc&size=128&bold=true&format=png",
    latestStatement: "European strategic autonomy is not optional — it is existential. We cannot depend on America for our security forever. Europe must grow up.",
    statementTimestamp: new Date(Date.now() - 28800000).toISOString(),
    impactLevel: "medium",
    statementLink: "https://www.elysee.fr/en",
    party: "Renaissance",
    inPowerSince: "2017-05-14",
  },
  {
    id: "kim-jong-un",
    name: "Kim Jong-un",
    country: "North Korea",
    countryCode: "KP",
    title: "Supreme Leader",
    photoUrl: "https://ui-avatars.com/api/?name=Kim+Jong-un&background=1a1a1a&color=d1d5db&size=128&bold=true&format=png",
    latestStatement: "Our nuclear deterrent is now complete. Any hostile act against the DPRK will be met with an overwhelming and devastating nuclear response.",
    statementTimestamp: new Date(Date.now() - 43200000).toISOString(),
    impactLevel: "high",
    statementLink: "https://kcna.kp",
    party: "Korean Workers' Party",
    inPowerSince: "2011-12-17",
  },
  {
    id: "mbs",
    name: "Mohammed bin Salman",
    country: "Saudi Arabia",
    countryCode: "SA",
    title: "Crown Prince & Prime Minister",
    photoUrl: "https://ui-avatars.com/api/?name=Mohammed+bin+Salman&background=1f1a0a&color=fde68a&size=128&bold=true&format=png",
    latestStatement: "Saudi Vision 2030 is transforming our kingdom. OPEC will continue to manage production to ensure market stability and fair pricing for all parties.",
    statementTimestamp: new Date(Date.now() - 36000000).toISOString(),
    impactLevel: "high",
    statementLink: "https://www.saudigov.sa",
    party: "Al Saud Royal Family",
    inPowerSince: "2017-06-21",
  },
];

router.get("/", (_req, res) => {
  res.json(leaders);
});

export default router;
